export enum Actions {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
}
export enum Subjects {
  Product = 'product',
  Category = 'category',
  Order = 'order',
  User = 'user',
  Role = 'role',
  Permission = 'permission',
  Inventory = 'inventory',
  Banner = 'banner',
  Cart = 'cart',
  Payment = 'payment',
  Promotion = 'promotion',
  Branch = 'branch',
  Brand = 'brand',
  Cloudinary = 'cloudinary',
  StockMovement = 'stockmovement',
  Transfer = 'transfer',
  Review = 'review',
  Benefit = 'benefit',
}
